[book]
authors = ["Evan Pratten"]
language = "en"
multilingual = false
src = "src"
title = "Software Development From Scratch"

[output.html]
mathjax-support = true
theme = "light"
default-theme = "light"
git-repository-url = "https://github.com/ewpratten/sdfs"
cname = "sdfs.retrylife.ca"

[output.html.search]
enable = true

[output.html.print]
enable = true